# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  gist_url = "https://gist.githubusercontent.com/hyunsuk/"
  uuid = "8529a9bcad5aabb993ce8e69005a1999"
  revision = "5c2ca4bfb3f55dfc7ca1d255daadcab7b58c40d2"
  
  provisioning_script_url = "#{gist_url}#{uuid}/raw/#{revision}/djangogirls.sh"

  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.define "djangogirls"
  config.vm.hostname = "djangogirls"

  config.vm.synced_folder "../",
    "/home/ubuntu/djangogirls",
    owner: "ubuntu",
    group: "ubuntu"

  config.vm.provision "shell", privileged: false, path: provisioning_script_url

  config.vm.provider :virtualbox do |vb|
    vb.name = "djangogirls"
    vb.cpus = 2
    vb.memory = 1024
  end
end
